### PR TITLE
Added TypeScript definition

### PR DESCRIPTION
**Pull request by oliverschwendener**
I added `index.d.ts` for TypeScript support.

### CODE REVIEW

**Comment by bayleedev** [comment]
@oliverschwendener can you give me a description of what this does? I'm not familiar with typescript.

**Comment by oliverschwendener** [comment]
@blainesch TypeScript is a superset of JavaScript which primarily provides optional static typing, classes and interfaces. One of the big benefits is to enable IDEs to provide a richer environment for spotting common errors as you type the code. People who use TypeScript (like myself) can use normal NPM packages which are written in JavaScript but the IDE can't provide information about the types unless there are type definitions available.

My PR adds type definitions to your package (affects only people using TypeScript).

The TypeScript compiler and the IDE now knows

...that there is a function called `convert`

image

...that the first argument `filePath` is type of `string`

image


...that the second argument `destination` is type of `string`

image

...that it returns a `Promise`

image

For example: when passing in a `number` as first argument, the TypeScript compiler/IDE can notify the developer that the first argument should be a `string` and mark it as invalid code:

image

On the other hand, when passing in correct values, the code is treated as valid:

image

Sorry for the long comment, but I wanted to be as precise as possible :)

**Comment by bayleedev** [comment]
Love it! Wow thank you so much for explaining this to me <3

**Comment by oliverschwendener** [comment]
Thank you for this project, you are welcome! Would be cool if you could publish a new release on npm

**Comment by oliverschwendener** [comment]
@blainesch can you please publish a new version on npm? :)

**Pull request merged**
